# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    vendor: true

    groups:
      rails:
        patterns:
          - actioncable
          - actionmailbox
          - actionmailer
          - actionpack
          - actiontext
          - actionview
          - activejob
          - activemodel
          - activerecord
          - activestorage
          - activesupport
          - rails
          - railties
      rubocop:
        patterns:
          - "rubocop"
          - "rubocop-*"
