shared:
  program_name: openSUSE Paste
  # Require a logged-in user (or a valid API key) before a paste can be posted.
  # Defaults to true. Set to false to allow anonymous posting.
  require_login_to_post: true

test:
  authentication:
    openid_connect:
      name: :suse

development:

production:
  authentication:
    openid_connect:
      name: :oidc
      scope:
      - :openid
      - :email
      - :profile
      response_type: :code
      uid_field: preferred_username
      client_options:
        port: 443
        scheme: https
        host: id.opensuse.org
        identifier: 
        secret: 
        redirect_uri: https://paste.opensuse.org/auth/oidc/callback
  sign_up_link: https://idp-portal.suse.com/univention/self-service/#page=createaccount
  theme: openSUSE
